RestaurantApp/Models/Waiters.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace RestaurantApp.Models
{
    public class Waiters
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }

        public int countTables { get; set; }
        public virtual ICollection<Tables> tables { get; set; }
        public Waiters() { 
            tables = new List<Tables>();
            countTables = 0;
        }
    }
}

RestaurantApp/Controllers/WaitersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RestaurantApp.Models;

namespace RestaurantApp.Controllers
{
    public class WaitersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Waiters
        public ActionResult Index()
        {
            foreach (var i in db.waiters.ToList())
            {

                i.countTables = i.tables.Count();

            }
            return View(db.waiters.ToList());
        }

        // GET: Waiters/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Waiters waiters = db.waiters.Find(id);
            if (waiters == null)
            {
                return HttpNotFound();
            }
            return View(waiters);
        }

        // GET: Waiters/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Waiters/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,countTables")] Waiters waiters)
        {
            if (ModelState.IsValid)
            {
                db.waiters.Add(waiters);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(waiters);
        }

        // GET: Waiters/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Waiters waiters = db.waiters.Find(id);
            if (waiters == null)
            {
                return HttpNotFound();
            }
            return View(waiters);
        }

        // POST: Waiters/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,countTables")] Waiters waiters)
        {
            if (ModelState.IsValid)
            {
                db.Entry(waiters).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(waiters);
        }

        // GET: Waiters/Delete/5
        [Authorize(Roles ="Owner")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Waiters waiters = db.waiters.Find(id);
            if (waiters == null)
            {
                return HttpNotFound();
            }
            return View(waiters);
        }

        // POST: Waiters/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize(Roles ="Owner")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Waiters waiters = db.waiters.Find(id);
            foreach (var table in waiters.tables.ToList())
            {
                db.tables.Remove(table); // Remove the table from the database
            }
            db.SaveChanges();
            db.waiters.Remove(waiters);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult AddToWaiter(int id)
        {
            var model = new AddTableToWaiter();
            model.waiterId = id;
            model.tables = db.tables.ToList();
            var waiter = db.waiters.Find(id);
            ViewBag.StoreName = waiter.Name;
            return View(model);

        }

        [HttpPost]
        public ActionResult AddToWaiter(AddTableToWaiter model)
        {
            var waiter = db.waiters.Find(model.waiterId);
            var table = db.tables.Find(model.tableId);
            waiter.tables.Add(table);
            //waiter.countTables++;
            db.waiters.Find(model.waiterId).countTables=waiter.tables.Count();
            db.SaveChanges();
            return RedirectToAction("Index", db.waiters.ToList());
        }
    }
}

RestaurantApp/Views/Waiters/AddToWaiter.cshtml
@model RestaurantApp.Models.AddTableToWaiter
@{
    ViewBag.Title = "AddToWaiter";
}

<h2>Add a table to the waiter: @ViewBag.StoreName </h2>

@using (Html.BeginForm("AddToWaiter", "Waiters"))
{
    <div class="form-group">
        @Html.DropDownListFor(m => m.tableId, new SelectList(Model.tables, "Id", "Name"), new { @class = "form-control" })
    </div>
    @Html.HiddenFor(m => m.waiterId)
    <button type="submit" class="btn btn-success">Add</button>

}

RestaurantApp/Views/Waiters/Create.cshtml
@model RestaurantApp.Models.Waiters

@{
    ViewBag.Title = "Create";
}

<h2>Add new waiter in this shift</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Waiters</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Tables for serving:
            <div class="col-md-10">
                @Html.EditorFor(model => model.countTables, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.countTables, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

RestaurantApp/Views/Waiters/Delete.cshtml
@model RestaurantApp.Models.Waiters

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Is the waiter finished with his/her shift?</h3>
<div>
    <h4>Details for the waiter</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            Served tables
        </dt>

        <dd>
            @Html.DisplayFor(model => model.countTables)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Dismiss" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

RestaurantApp/Views/Waiters/Details.cshtml
@model RestaurantApp.Models.Waiters

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Waiters</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
           Number of tables served in the whole shift:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.countTables)
        </dd>

        <dt>
            Tables for serving:
        </dt>

        <dd>
            @foreach(var table in Model.tables)
            {
                @Html.DisplayFor(t =>table.Name);
                <br />
            }
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

RestaurantApp/Views/Waiters/Edit.cshtml
@model RestaurantApp.Models.Waiters

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Waiters</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <br />
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            @Html.ActionLink("Add table to the waiter", "AddToWaiter", new { id = Model.Id })
        </div>
    </div>
    <br />

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

RestaurantApp/Views/Waiters/Index.cshtml
@model IEnumerable<RestaurantApp.Models.Waiters>

@{
    ViewBag.Title = "Index";
}

<h2>Active waiters in this shift</h2>
<div>
    @if (User.IsInRole("Owner"))
    {
    <img src="https://www.escoffier.edu/wp-content/uploads/2022/04/Restaurant-manager-having-a-conversation-with-chef-with-laptop-on-table-768.jpeg" style="width:200px; height:150px; display:inline-block" />
    }
    @if (User.IsInRole("Waiter"))
    {
    <img src="https://media.istockphoto.com/id/661130682/photo/waiter-and-waitress-holding-a-serving-tray-with-glass-of-cocktail.jpg?s=612x612&w=0&k=20&c=0KbmzYTZ2an04--DjW8cQuYt0OvmZSvnp9JJbXP1cbQ=" style="width:200px; height:150px; display:inline-block" />
    }
</div>
<br />

<p>
    @Html.ActionLink("Add New", "Create")
</p>
<table class="table" id="tablesId">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                Tables serving for the whole shift
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.countTables)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @if (User.IsInRole("Owner"))
                    {
                        @Html.ActionLink("Finish shift", "Delete", new { id = item.Id })
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

@section scripts{
    <script>
        $(document).ready(function () {
            var table = $("#tablesId").DataTable();
            $("#tablesId .js-delete").on("click", function () {
               // alert("Raboti click");
                var button = $(this);
                bootbox.confirm("Close the bill?", function (result) {
                    if (result) {
                        $.ajax({
                            url: "/api/TablesAPI/" + button.attr("data-table-id"),
                            method: "DELETE",
                            success: function () {
                                table.row(button.parents("tr")).remove().draw();
                            }, error: function (err) {
                                console.log(err);
                            }
                        });
                    }
                });

            });
        });
    </script>
}