RestaurantApp/Controllers/TablesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RestaurantApp.Models;

namespace RestaurantApp.Controllers
{
    public class TablesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Tables
        public ActionResult Index()
        {
            return View(db.tables.ToList());
        }

        // GET: Tables/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tables tables = db.tables.Find(id);
            if (tables == null)
            {
                return HttpNotFound();
            }
            return View(tables);
        }

        // GET: Tables/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Tables/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Capacity,Bill")] Tables tables)
        {
            if (ModelState.IsValid)
            {
                db.tables.Add(tables);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tables);
        }

        // GET: Tables/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tables tables = db.tables.Find(id);
            if (tables == null)
            {
                return HttpNotFound();
            }
            return View(tables);
        }

        // POST: Tables/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Capacity,Bill")] Tables tables)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tables).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tables);
        }

        // GET: Tables/Delete/5
        /*public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tables tables = db.tables.Find(id);
            if (tables == null)
            {
                return HttpNotFound();
            }
            return View(tables);
        }*/

        // POST: Tables/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {

            //Tables tables = db.tables.Find(id);
            Tables tables = db.tables.Include(t => t.items).SingleOrDefault(t => t.Id == id);
            foreach (var item in tables.items.ToList())
            {
                tables.items.Remove(item);
               // db.items.Remove(item);
              // db.SaveChanges();
            }
            
            if (tables.waiter != null)
            {
                db.waiters.Find(db.tables.Find(id).waiter.Id).countTables--;
                db.waiters.Find(db.tables.Find(id).waiter.Id).tables.Remove(tables);
               // db.waiters.Find(tables.waiter.Id).countTables-=1;
                tables.waiter.countTables--;
                //db.Entry(tables.waiter).State = EntityState.Modified;
               // db.SaveChanges();
            }
           // tables.waiter = null;
            db.tables.Remove(tables);
            //db.SaveChanges();
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult AddToTable(int id)
        {
            var model = new AddItemToTable();
            model.tableId = id;
            model.items = db.items.ToList();
            var store = db.tables.Find(id);
            ViewBag.StoreName = store.Name;
            return View(model);

        }

        [HttpPost]
        public ActionResult AddToTable(AddItemToTable model)
        {
            var table = db.tables.Find(model.tableId);
            var item = db.items.Find(model.itemId);
            table.items.Add(item);
            table.Bill += item.Price;
            db.SaveChanges();
            return View("Index", db.tables.ToList());
        }

    }
}

RestaurantApp/Views/Tables/AddToTable.cshtml
@model RestaurantApp.Models.AddItemToTable
@{
    ViewBag.Title = "AddToTable";
}

<h2>Order new thing: @ViewBag.StoreName </h2>

@using (Html.BeginForm("AddToTable", "Tables"))
{
    <div class="form-group">
        @Html.DropDownListFor(m => m.itemId, new SelectList(Model.items, "Id", "Name"), new { @class = "form-control" })
    </div>
    @Html.HiddenFor(m => m.tableId)
    <button type="submit" class="btn btn-success">Add</button>

}

RestaurantApp/Views/Tables/Create.cshtml
@model RestaurantApp.Models.Tables

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Tables</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Capacity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Capacity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Capacity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Bill, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Bill, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Bill, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RestaurantApp/Views/Tables/Delete.cshtml
@model RestaurantApp.Models.Tables

@{
    ViewBag.Title = "Delete";
}

<h2>Closing the bill</h2>

<h3>Are you sure you want to close the bill?</h3>
<div>
    <h4>Tables</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Capacity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Capacity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Bill)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Bill)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

RestaurantApp/Views/Tables/Details.cshtml
@model RestaurantApp.Models.Tables

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Tables</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Capacity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Capacity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Bill)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Bill)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Close the bill", "Delete", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

RestaurantApp/Views/Tables/Edit.cshtml
@model RestaurantApp.Models.Tables

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Tables</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Capacity, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Capacity, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Capacity, "", new { @class = "text-danger" })
        </div>
    </div>


     <br />
    <br />
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            @Html.ActionLink("Add items to the table","AddToTable", new {id= Model.Id})
        </div>
    </div>
    <br />
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RestaurantApp/Views/Tables/Index.cshtml
@model IEnumerable<RestaurantApp.Models.Tables>

@{
    ViewBag.Title = "Index";
}

<h2>Occupied tables at the moment</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table" id="tablesId">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Capacity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Bill)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Capacity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Bill)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    <button data-table-id="@item.Id" type="submit" class="btn-link js-delete">Pay the bill</button>
                </td>
            </tr>

        }
    </tbody>
</table>

@section scripts{
    <script>
        $(document).ready(function () {
            var table = $("#tablesId").DataTable();
            $("#tablesId .js-delete").on("click", function () {
               // alert("Raboti click");
                var button = $(this);
                bootbox.confirm("Close the bill?", function (result) {
                    if (result) {
                        $.ajax({
                            url: "/api/TablesAPI/" + button.attr("data-table-id"),
                            method: "DELETE",
                            success: function () {
                                table.row(button.parents("tr")).remove().draw();
                            }, error: function (err) {
                                console.log(err);
                            }
                        });
                    }
                });
               
            });
        });
    </script>
}